#### Just watching , without doing anything how much accuracy I m getting.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [4]:
new_df= df.sample(50000)

In [5]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       1
is_duplicate    0
dtype: int64

In [6]:
new_df.dropna(inplace=True)

In [7]:
que_df= new_df[['question1', 'question2']]

In [8]:
que_df.head()

,question1,question2
67595,What are the margins (%) given to paint distri...,What are the margins (%) given to distributors...
258302,I am traveling to Singapore. Where is it best ...,I plan to visit Nice and also want to go to Pa...
321905,"How many genders, or sexes, are there?",How many of you have name that can be used for...
340724,"How cold can the Gobi Desert get, and how do i...","How cold can the Gobi Desert get, and how do i..."
325430,What is your review of Introduction to Computa...,Could you program a video game entirely using ...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
questions= list(que_df['question1']) + list(que_df['question2'])

cv = CountVectorizer(max_features= 5000)
q1_arr, q2_arr= np.vsplit(cv.fit_transform(questions).toarray(), 2)

In [10]:
temp_df1= pd.DataFrame(q1_arr, index= que_df.index)
temp_df2= pd.DataFrame(q2_arr, index= que_df.index)
temp_df= pd.concat([temp_df1, temp_df2], axis=1)

In [11]:
temp_df.shape

(49999, 10000)

In [12]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [13]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,is_duplicate
67595,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
258302,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
321905,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
340724,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
325430,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(temp_df.iloc[:, :-1].values, temp_df.iloc[:, -1].values, test_size=0.2, random_state=42)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
rf= RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred= rf.predict(x_test)
confusion_matrix(y_test, y_pred)

array([[5839,  511],
       [1977, 1673]], dtype=int64)

In [16]:
accuracy_score(y_test, y_pred)

0.7512